spring.application.name=FilmCampBackend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

server.servlet.session.persistent=false
#If true or not mentioned Tomcat saves the session even after the application is restarted in disk storage.
#which means not login required even after restarting the application.

spring.config.import=optional:file:.env[.properties]
app.frontend-url=${FRONTEND_URL}
app.frontend-url2=${FRONTEND_URL2}

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true